# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  About: /about

# Logo Image Source
logo_src: /images/glasses.svg

# Theme Main Subtitle
subtitle_main: ShadowWood's Blog

# Theme Secondary subtitle
susbtitle_secondary: 睡睡觉，玩玩游戏编编程

# Footer About Section
about_footer: Shadow Wood<br/><a herf="#">shadowwood@foxmail.com</a>

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: /images/450x450.jpeg

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates: true

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  # disqus_shortname: shadowwood
  # Facebook comments
  # facebook:
  #   appid: shadowwood
  #   comment_count: 5
  #   comment_colorscheme: light
  # Gitalk comments
  gitalk:
    clientID: 3c20f2c5396af1661cdd
    clientSecret: 0d22e72a163265bb03f44e550c73d779bc47315f
    repo: shadowwood.github.io
    owner: ShadowWood
    admin:
      - ShadowWood

# Google Analytics Tracking ID
# google_analytics:

# Baidu Analytics Tracking ID
baidu_analytics: 818f68a34fb7ee2d3343ec7bce3a06d5

# Social Accounts
twitter_url: 
facebook_url: 
instagram_url:
dribble_url:
googleplus_url:
behance_url:
fivehundredpx_url:
email_url: shadowwood@foxmail.com
github_url: https://github.com/ShadowWood
rss_url: /atom.xml
